'use strict';
// Standalone HTML report for a contract run.

const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function pretty(text) {
  if (text === null || text === undefined) return '';
  try { return JSON.stringify(JSON.parse(text), null, 2); } catch { return String(text); }
}

function htmlReport(run) {
  const s = run.summary || {};
  const rows = (run.steps || []).map((st, i) => {
    const req = st.request || {};
    const res = st.response || {};
    const checks = (st.checks || []).map((c) => `<li class="${esc(c.status)}"><b>${esc(c.status)}</b> ${esc(c.name)} — ${esc(c.message)}${
      c.errors ? `<ul>${c.errors.map((e) => `<li><code>${esc(e.pointer || '/')}</code> ${esc(e.message)}${e.hint ? `<br><em>${esc(e.hint)}</em>` : ''}</li>`).join('')}</ul>` : ''}</li>`).join('');
    return `<details class="step ${esc(st.outcome)}"${st.outcome === 'fail' ? ' open' : ''}>
<summary><span class="badge ${esc(st.outcome)}">${esc(st.outcome)}</span> <span class="n">#${i + 1}</span>
<code>${esc(st.opId)}</code> ${st.kind === 'negative' ? `<span class="neg">negative: ${esc(st.test)}</span>` : ''}
<span class="meta">${res.status ? `HTTP ${res.status}` : esc(st.error || '')} ${res.durationMs ? `· ${res.durationMs} ms` : ''}</span></summary>
<div class="grid"><div><h4>Request</h4><pre>${esc(req.method)} ${esc(req.url)}\n${Object.entries(req.headers || {}).map(([k, v]) => `${esc(k)}: ${esc(v)}`).join('\n')}${req.body ? `\n\n${esc(pretty(req.body))}` : ''}</pre></div>
<div><h4>Response</h4><pre>${res.status ? `HTTP ${res.status} ${esc(res.statusText || '')}\n${Object.entries(res.headers || {}).map(([k, v]) => `${esc(k)}: ${esc(v)}`).join('\n')}\n\n${esc(pretty(res.body).slice(0, 20000))}` : esc(st.error || '')}</pre></div></div>
<h4>Checks</h4><ul class="checks">${checks}</ul></details>`;
  }).join('\n');

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Contract run · ${esc(run.specName)}</title>
<style>
:root{--bg:#f7f8fa;--card:#fff;--fg:#1c2230;--muted:#5d6678;--border:#dfe3ea;--pass:#1a7f37;--warn:#9a6700;--fail:#cf222e;--code:#eef1f5}
@media (prefers-color-scheme:dark){:root{--bg:#0e1117;--card:#161b22;--fg:#e6edf3;--muted:#8b949e;--border:#30363d;--pass:#3fb950;--warn:#d29922;--fail:#f85149;--code:#1f2630}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.5 system-ui,-apple-system,sans-serif;padding:24px 16px}
main{max-width:1100px;margin:0 auto}h1{font-size:22px;margin:0 0 4px}.sub{color:var(--muted);margin-bottom:16px}
.cards{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:20px}.card{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:12px 16px;min-width:120px}
.card b{display:block;font-size:22px}.step{background:var(--card);border:1px solid var(--border);border-radius:10px;margin:8px 0;padding:8px 12px}
summary{cursor:pointer;display:flex;gap:8px;align-items:center;flex-wrap:wrap}.badge{font-size:11px;text-transform:uppercase;font-weight:700;padding:2px 8px;border-radius:99px;color:#fff}
.badge.pass{background:var(--pass)}.badge.warn{background:var(--warn)}.badge.fail{background:var(--fail)}.n,.meta{color:var(--muted)}.neg{font-size:12px;border:1px solid var(--border);border-radius:6px;padding:0 6px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media (max-width:760px){.grid{grid-template-columns:1fr}}
pre{background:var(--code);border-radius:8px;padding:10px;overflow:auto;max-height:420px;font-size:12px;white-space:pre-wrap;word-break:break-word}
.checks li.pass b{color:var(--pass)}.checks li.warn b{color:var(--warn)}.checks li.fail b{color:var(--fail)}code{font-family:ui-monospace,monospace}
</style></head><body><main>
<h1>${esc(run.specName)}</h1>
<div class="sub">Target <code>${esc(run.target?.baseUrl || '')}</code> · started ${esc(run.startedAt)} · ${esc(run.durationMs)} ms · lenient allOf: ${run.options?.lenientAllOf ? 'on' : 'off'} · negative tests: ${run.options?.negative ? 'on' : 'off'}</div>
<div class="cards"><div class="card"><b>${s.total ?? 0}</b>steps</div><div class="card"><b style="color:var(--pass)">${s.passed ?? 0}</b>passed</div>
<div class="card"><b style="color:var(--warn)">${s.warned ?? 0}</b>warnings</div><div class="card"><b style="color:var(--fail)">${s.failed ?? 0}</b>failed</div></div>
${rows}
<p class="sub">Generated by api-test-tool.</p></main></body></html>`;
}

module.exports = { htmlReport };
